### ISSUE TITLE
Projeto sem atualização

### ISSUE THREAD

**Issue by jlsilva01** [thiagoalmeiidaaa/projeto_final_bd2_satc_2024#1]
@thiagoalmeiidaaa o repositório não teve nenhuma alteração há quase uma semana.
Sugiro revalidarem a distribução das tarefas para que tenha commits frequentes neste repositório indicando o trabalho contínuo do mesmo.
Dúvida, me avisem.

**Comment by gabrielfrello** [comment]
As funções foram definidas pelo grupo da seguinte maneira: 

- Front-End
-> Gabriel Boelter
-> Igor Steiner
-> Larissa Maximiano

- Back-End
-> Thiago Almeida
-> Augusto Frelo
-> Gabriel Tassi

- Dicionário de Dados:
-> Gabriel Boelter

- Modelo Word:
-> A definir

- Modelo Físico:
-> Gabriel Tassi
-> Thiago Almeida

- Scripts SQL:
-> Augusto Frelo
-> Thiago Almeida
-> Gabriel Tassi

- Relatório Final:
-> Gabriel Boelter
-> Igor Steiner
-> Larissa Maximiano

- Código Fonte do CRUD
-> A definir
