### ISSUE TITLE
Criação do modelo físico

### ISSUE THREAD

**Issue by IgorSteinerS** [thiagoalmeiidaaa/projeto_final_bd2_satc_2024#2]

**Comment by gabrielfrello** [comment]
11/06 -> Modelo Físico feito por @gabrielfrello e @thiagoalmeiidaaa, via dbdiagram.io.

13/06 -> Atualização feita para melhorar qualidade da imagem do Modelo Físico, realizada pelo @IgorSteinerS.

https://dbdiagram.io/d/666b3fada179551be6d56ac5
