### ISSUE TITLE
Documentar o dicionário de dados

### ISSUE THREAD

**Issue by IgorSteinerS** [thiagoalmeiidaaa/projeto_final_bd2_satc_2024#3]

**Comment by GabrielBoelter** [comment]
Dia 11/06/2024
Foi iniciado o preenchimento do dicionário de dados.
Dia 18/06/2024
Preenchido todas as tabelas com descrição e colunas.

Fica pendente o preenchimentos dos índices e revisar as tabelas.

**Comment by GabrielBoelter** [comment]
24/06/2024
Índices preenchidos, porém falta organiza-los.

**Comment by th-almeida** [comment]
Dicionario de dados finalizado.
