### ISSUE TITLE
Fazer o script do banco de dados

### ISSUE THREAD

**Issue by LarissaDeMattia** [thiagoalmeiidaaa/projeto_final_bd2_satc_2024#4]

**Comment by th-almeida** [comment]
Feitos todos os Scripts de SQL no arquivo [scripts_sql](https://github.com/thiagoalmeiidaaa/projeto_final_bd2_satc_2024/tree/a38789cd5070fde770fee2b4d05bb10b75a9a7fd/scripts_sql)
