### ISSUE TITLE
Fazer o front-end

### ISSUE THREAD

**Issue by LarissaDeMattia** [thiagoalmeiidaaa/projeto_final_bd2_satc_2024#5]

**Comment by GabrielBoelter** [comment]
Dia 18/06/2024
Finalizei a estilização da tela de Login do projeto, comitando apenas o html e css pois o código php está em andamento.
[index.zip](https://github.com/user-attachments/files/15893788/index.zip)

**Comment by IgorSteinerS** [comment]
Dia 18/06/2024
Comecei a criação e estilização da tela transações.
[transacoes.zip](https://github.com/user-attachments/files/15893827/transacoes.zip)

**Comment by LarissaDeMattia** [comment]
Dia 18/06/2024
Fiz a tela que aparece depois do login.
[painel.zip](https://github.com/user-attachments/files/15893829/painel.zip)

**Comment by LarissaDeMattia** [comment]
Dia 19/06/2024
Padronização do css dos arquivos painel.html e transacoes.html com index.html

**Comment by LarissaDeMattia** [comment]
20/06/2024
Fiz a tela dos cartões de crédito e a tela do extrato. 
Não integrei com o banco de dados

**Comment by GabrielBoelter** [comment]
24/06/2024
Front-end de todas as telas finalizadas e padronizadas.

**Comment by gabrielfrello** [comment]
Banco de dados implementado após a finalização das telas feitas pelo pessoal responsável.
